# ?? MongoDB ??????????????????????????????????????????
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=challan_db

# Add this line to application.properties
gemini.model.name=gemini-2.5-flash

# ?? Gemini API ????????????????????????????????????????
gemini.api.key=YOUR_NEW_API_KEY_HERE

# ?? Server ????????????????????????????????????????????
server.port=8080

# ?? Logging ???????????????????????????????????????????
logging.level.com.challan=DEBUG
